version: '3.4'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes
    restart: on-failure
  sidekiq:
    build: .
    command: bundle exec sidekiq
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
  rails:
    build: .
    command: bash -c "export SECRET_KEY_BASE=$(bundle exec rake secret) && RAILS_ENV=production bundle exec rake assets:precompile && RAILS_ENV=production bundle exec rails s -p 3000"
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - .:/app
      - db-data:/app/db
    depends_on:
      - redis
      - sidekiq
volumes:
  db-data: